version: "3"
services:
  app:
    image: #################### EINFÜGEN ####################
    ports:
      - "3000:3000" # forward webserver on standard-http port
    depends_on:
      - mongodbservice
  mongodbservice:
    image: mongo # to be retrieved from dockerhub
    ports:
      - "27017:27017" # forward mongod port
    volumes:
    - ./data:/data/db
